# Generated by Django 2.2.9 on 2023-01-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=20, null=True),
        ),
    ]
