# Generated by Django 2.2.9 on 2023-01-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221226_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
