# Generated by Django 2.2.9 on 2023-01-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230109_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer')], max_length=20, null=True),
        ),
    ]
