# Generated by Django 2.2.9 on 2023-02-09 17:31

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='foto',
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='../../../static/admin/img/login.webp', null=True, upload_to=store.models.get_fileupload_path),
        ),
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('buyer', 'buyer')], max_length=20, null=True),
        ),
    ]
