# Generated by Django 2.2.9 on 2023-04-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_history_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History_Product',
        ),
    ]
