# Generated by Django 2.2.9 on 2023-04-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_history_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='record_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.History_Product'),
        ),
    ]
