# Generated by Django 2.2.9 on 2023-04-02 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_record_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='record_transaction',
        ),
        migrations.AddField(
            model_name='history_product',
            name='record_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_transaction', to='store.Order'),
        ),
    ]
