# Generated by Django 2.2.9 on 2023-04-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20230402_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_product',
            name='record_transaction',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='history_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.History_Product'),
        ),
    ]
