# Generated by Django 2.2.9 on 2023-04-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230402_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='history_product',
        ),
        migrations.AddField(
            model_name='history_product',
            name='record_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_transaction', to='store.OrderItem'),
        ),
    ]
